### ISSUE TITLE
<Question> Dual boot under eMMC

### ISSUE THREAD

**Issue by Vliro** [altreact/archbk#5]
I was wondering if it is possible to use this script to dual-boot ChromeOS and Arch under eMMC, or is it only possible to boot Arch from SD? Regards

**Comment by altreact** [comment]
It may be possible, yet currently I don't have the knowledge, or the time to acquire the necessary knowledge to make that possible.

Chromeos uses over 10 partitions on the emmc. I'm not sure offhand which partition is used for what, or if chromeos plays nicely with other OS's on the same storage device.

Plus, storage space is very limited on every Chromebook I've come across. 16gb can be used up very quickly in arch Linux, especially if one uses arch on a Chromebook as a daily machine.

Arch requires a little bit of tweaking, yet when an arch system is built, it can do anything chromeos does, plus much more, considering that chromeos is basically an operating system built around chrome web browser.

**Comment by Vliro** [comment]
Thank you for your answer.
I have 64gb, so storage shouldn't be an issue anyways.
I am considering installing Arch over Chrome, I just have a few questions if you don't mind.
1) If I have modified Arch on my SD will all settings move over to the eMMC?
2) If I create a recovery disk beforehand I can always revert back completely to Chrome OS?
3) The GPU on R13 is not supported, only on Chrome OS, right? That means I cannot get any video HW acceleration in Linux?
Thank you for your time helping a newbie to the Chromebook sect.

**Comment by altreact** [comment]
Good luck with the dual boot. I'm sure that it can be done.

[This](https://github.com/altreact/archbk-utils) may work on the R13; essentially cloning you exact configurations and programs over to emmc.

Correct. As long as you don't alter the bootloader in any way (which this arch install message doesn't do), you'll be able to restore chromeos on your Chromebook.

I have no idea what hardware / software compatibility issues the r13 will have with ArchLinux ARM. I've never had my hands on one.

FYI - I am by no means a Arch Linux ARM guru. I'm just a guy that wanted to learn shell scripting,and decided to modify a script I wrote (that would install Arch Linux ARM on my Samsung Chromebook), and modified it so that other people could benefit from it.

The community at [Arch Linux ARM](archlinuxarm.org/)is amazing, and a lot more knowledgeable and familiar with how to go about getting Arch Linux ARM to work right on your machine.

Side note:
Search engines are your friend. Quick searches will answer a lot, if not all of your Arch Linux ARM on r13 questions better than I can.
